cd ./TUMVI/magistrale

wget --header 'Host: cdn2.vision.in.tum.de' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:138.0) Gecko/20100101 Firefox/138.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Language: en-US,en;q=0.5' --referer 'https://cvg.cit.tum.de/' --header 'Upgrade-Insecure-Requests: 1' --header 'Sec-Fetch-Dest: document' --header 'Sec-Fetch-Mode: navigate' --header 'Sec-Fetch-Site: same-site' --header 'Sec-Fetch-User: ?1' 'https://cdn2.vision.in.tum.de/tumvi/exported/euroc/512_16/dataset-magistrale1_512_16.tar' --output-document 'dataset-magistrale1_512_16.tar'


wget --header 'Host: cdn2.vision.in.tum.de' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:138.0) Gecko/20100101 Firefox/138.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Language: en-US,en;q=0.5' --referer 'https://cvg.cit.tum.de/' --header 'Upgrade-Insecure-Requests: 1' --header 'Sec-Fetch-Dest: document' --header 'Sec-Fetch-Mode: navigate' --header 'Sec-Fetch-Site: same-site' --header 'Sec-Fetch-User: ?1' 'https://cdn2.vision.in.tum.de/tumvi/exported/euroc/512_16/dataset-magistrale2_512_16.tar' --output-document 'dataset-magistrale2_512_16.tar'

wget --header 'Host: cdn2.vision.in.tum.de' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:138.0) Gecko/20100101 Firefox/138.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Language: en-US,en;q=0.5' --referer 'https://cvg.cit.tum.de/' --header 'Upgrade-Insecure-Requests: 1' --header 'Sec-Fetch-Dest: document' --header 'Sec-Fetch-Mode: navigate' --header 'Sec-Fetch-Site: same-site' --header 'Sec-Fetch-User: ?1' 'https://cdn2.vision.in.tum.de/tumvi/exported/euroc/512_16/dataset-magistrale3_512_16.tar' --output-document 'dataset-magistrale3_512_16.tar'

wget --header 'Host: cdn2.vision.in.tum.de' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:138.0) Gecko/20100101 Firefox/138.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Language: en-US,en;q=0.5' --referer 'https://cvg.cit.tum.de/' --header 'Upgrade-Insecure-Requests: 1' --header 'Sec-Fetch-Dest: document' --header 'Sec-Fetch-Mode: navigate' --header 'Sec-Fetch-Site: same-site' --header 'Sec-Fetch-User: ?1' 'https://cdn2.vision.in.tum.de/tumvi/exported/euroc/512_16/dataset-magistrale4_512_16.tar' --output-document 'dataset-magistrale4_512_16.tar'

wget --header 'Host: cdn2.vision.in.tum.de' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:138.0) Gecko/20100101 Firefox/138.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Language: en-US,en;q=0.5' --referer 'https://cvg.cit.tum.de/' --header 'Upgrade-Insecure-Requests: 1' --header 'Sec-Fetch-Dest: document' --header 'Sec-Fetch-Mode: navigate' --header 'Sec-Fetch-Site: same-site' --header 'Sec-Fetch-User: ?1' 'https://cdn2.vision.in.tum.de/tumvi/exported/euroc/512_16/dataset-magistrale5_512_16.tar' --output-document 'dataset-magistrale5_512_16.tar'

wget --header 'Host: cdn2.vision.in.tum.de' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:138.0) Gecko/20100101 Firefox/138.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Language: en-US,en;q=0.5' --referer 'https://cvg.cit.tum.de/' --header 'Upgrade-Insecure-Requests: 1' --header 'Sec-Fetch-Dest: document' --header 'Sec-Fetch-Mode: navigate' --header 'Sec-Fetch-Site: same-site' --header 'Sec-Fetch-User: ?1' 'https://cdn2.vision.in.tum.de/tumvi/exported/euroc/512_16/dataset-magistrale6_512_16.tar' --output-document 'dataset-magistrale6_512_16.tar'

cd ..
mkdir outdoor
cd outdoor/

wget --header 'Host: cdn2.vision.in.tum.de' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:138.0) Gecko/20100101 Firefox/138.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Language: en-US,en;q=0.5' --referer 'https://cvg.cit.tum.de/' --header 'Upgrade-Insecure-Requests: 1' --header 'Sec-Fetch-Dest: document' --header 'Sec-Fetch-Mode: navigate' --header 'Sec-Fetch-Site: same-site' --header 'Sec-Fetch-User: ?1' 'https://cdn2.vision.in.tum.de/tumvi/exported/euroc/512_16/dataset-outdoors1_512_16.tar' --output-document 'dataset-outdoors1_512_16.tar'

wget --header 'Host: cdn2.vision.in.tum.de' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:138.0) Gecko/20100101 Firefox/138.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Language: en-US,en;q=0.5' --referer 'https://cvg.cit.tum.de/' --header 'Upgrade-Insecure-Requests: 1' --header 'Sec-Fetch-Dest: document' --header 'Sec-Fetch-Mode: navigate' --header 'Sec-Fetch-Site: same-site' --header 'Sec-Fetch-User: ?1' 'https://cdn2.vision.in.tum.de/tumvi/exported/euroc/512_16/dataset-outdoors2_512_16.tar' --output-document 'dataset-outdoors2_512_16.tar'

wget --header 'Host: cdn2.vision.in.tum.de' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:138.0) Gecko/20100101 Firefox/138.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Language: en-US,en;q=0.5' --referer 'https://cvg.cit.tum.de/' --header 'Upgrade-Insecure-Requests: 1' --header 'Sec-Fetch-Dest: document' --header 'Sec-Fetch-Mode: navigate' --header 'Sec-Fetch-Site: same-site' --header 'Sec-Fetch-User: ?1' 'https://cdn2.vision.in.tum.de/tumvi/exported/euroc/512_16/dataset-outdoors3_512_16.tar' --output-document 'dataset-outdoors3_512_16.tar'

wget --header 'Host: cdn2.vision.in.tum.de' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:138.0) Gecko/20100101 Firefox/138.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Language: en-US,en;q=0.5' --referer 'https://cvg.cit.tum.de/' --header 'Upgrade-Insecure-Requests: 1' --header 'Sec-Fetch-Dest: document' --header 'Sec-Fetch-Mode: navigate' --header 'Sec-Fetch-Site: same-site' --header 'Sec-Fetch-User: ?1' 'https://cdn2.vision.in.tum.de/tumvi/exported/euroc/512_16/dataset-outdoors4_512_16.tar' --output-document 'dataset-outdoors4_512_16.tar'

wget --header 'Host: cdn2.vision.in.tum.de' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:138.0) Gecko/20100101 Firefox/138.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Language: en-US,en;q=0.5' --referer 'https://cvg.cit.tum.de/' --header 'Upgrade-Insecure-Requests: 1' --header 'Sec-Fetch-Dest: document' --header 'Sec-Fetch-Mode: navigate' --header 'Sec-Fetch-Site: same-site' --header 'Sec-Fetch-User: ?1' 'https://cdn2.vision.in.tum.de/tumvi/exported/euroc/512_16/dataset-outdoors5_512_16.tar' --output-document 'dataset-outdoors5_512_16.tar'

wget --header 'Host: cdn2.vision.in.tum.de' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:138.0) Gecko/20100101 Firefox/138.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Language: en-US,en;q=0.5' --referer 'https://cvg.cit.tum.de/' --header 'Upgrade-Insecure-Requests: 1' --header 'Sec-Fetch-Dest: document' --header 'Sec-Fetch-Mode: navigate' --header 'Sec-Fetch-Site: same-site' --header 'Sec-Fetch-User: ?1' 'https://cdn2.vision.in.tum.de/tumvi/exported/euroc/512_16/dataset-outdoors6_512_16.tar' --output-document 'dataset-outdoors6_512_16.tar'

wget --header 'Host: cdn2.vision.in.tum.de' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:138.0) Gecko/20100101 Firefox/138.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Language: en-US,en;q=0.5' --referer 'https://cvg.cit.tum.de/' --header 'Upgrade-Insecure-Requests: 1' --header 'Sec-Fetch-Dest: document' --header 'Sec-Fetch-Mode: navigate' --header 'Sec-Fetch-Site: same-site' --header 'Sec-Fetch-User: ?1' 'https://cdn2.vision.in.tum.de/tumvi/exported/euroc/512_16/dataset-outdoors7_512_16.tar' --output-document 'dataset-outdoors7_512_16.tar'

wget --header 'Host: cdn2.vision.in.tum.de' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:138.0) Gecko/20100101 Firefox/138.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Language: en-US,en;q=0.5' --referer 'https://cvg.cit.tum.de/' --header 'Upgrade-Insecure-Requests: 1' --header 'Sec-Fetch-Dest: document' --header 'Sec-Fetch-Mode: navigate' --header 'Sec-Fetch-Site: same-site' --header 'Sec-Fetch-User: ?1' 'https://cdn2.vision.in.tum.de/tumvi/exported/euroc/512_16/dataset-outdoors8_512_16.tar' --output-document 'dataset-outdoors8_512_16.tar'